version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-phex
    ports:
      - "70:70"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs
      - ./logs:/var/log/nginx
    networks:
      - nginx-network

networks:
  nginx-network:
    external: true
